name: Changeset
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    env:
      HUSKY: 0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          scope: "@fatduckai"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build Packages
        run: bun run build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run version-packages
          publish: |
            # Replace workspace protocol with actual versions before publishing
            node -e "
              const fs = require('fs');
              const path = require('path');
              
              const cliPkgPath = './apps/cli/package.json';
              const corePkgPath = './packages/core/package.json';
              
              const cliPkg = JSON.parse(fs.readFileSync(cliPkgPath, 'utf8'));
              const corePkg = JSON.parse(fs.readFileSync(corePkgPath, 'utf8'));
              
              if (cliPkg.dependencies['@fatduckai/core'] === 'workspace:*') {
                console.log('Replacing workspace:* with actual version');
                cliPkg.dependencies['@fatduckai/core'] = '^' + corePkg.version;
                fs.writeFileSync(cliPkgPath, JSON.stringify(cliPkg, null, 2) + '\n');
              }
            "
            bun run release
          commit: "chore: update versions"
          title: "chore: update versions"

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run version-packages
          publish: bun run release
          commit: "chore: update versions"
          title: "chore: update versions"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
